# Generated by Django 6.0.3 on 2026-03-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier for the frontend (e.g. 'Architect').",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "github_username",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("avatar_url", models.URLField(blank=True, default="")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("Founder", "Founder"),
                            ("Lead", "Lead"),
                            ("Mentor", "Mentor"),
                            ("Member", "Member"),
                            ("Learner", "Learner"),
                        ],
                        db_index=True,
                        default="Learner",
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=0,
                        help_text="Weighted merit score (cached, recomputed periodically).",
                        max_digits=10,
                    ),
                ),
                (
                    "contributions_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of tracked contributions (cached).",
                    ),
                ),
                (
                    "impact",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Percentile rank among active members, 0–100 (cached).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-score", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScoringWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("PR_MERGED", "Pull Request Merged"),
                            ("CODE_REVIEW", "Code Review"),
                            ("ISSUE_CLOSED", "Issue Closed"),
                            ("COMMIT", "Commit"),
                            ("RELEASE", "Release"),
                            ("DISCUSSION", "Discussion"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Points awarded per contribution of this type.",
                        max_digits=6,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-weight"],
            },
        ),
        migrations.CreateModel(
            name="MemberBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_members",
                        to="members.badge",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_badges",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("member", "badge")},
            },
        ),
        migrations.AddField(
            model_name="member",
            name="badges",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                through="members.MemberBadge",
                to="members.badge",
            ),
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("PR_MERGED", "Pull Request Merged"),
                            ("CODE_REVIEW", "Code Review"),
                            ("ISSUE_CLOSED", "Issue Closed"),
                            ("COMMIT", "Commit"),
                            ("RELEASE", "Release"),
                            ("DISCUSSION", "Discussion"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "github_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique GitHub identifier for deduplication.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, default="")),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Computed point value based on scoring weight.",
                        max_digits=8,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        help_text="When this contribution occurred on GitHub."
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributions",
                        to="projects.project",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "contribution_type"],
                        name="idx_contrib_member_type",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["-score"], name="idx_member_score_desc"),
        ),
    ]
