# Generated by Django 6.0.3 on 2026-03-07 07:09

from decimal import Decimal

from django.db import migrations

DEFAULT_WEIGHTS = [
    ("PR_MERGED", Decimal("10.00"), "Points for a merged pull request."),
    ("CODE_REVIEW", Decimal("7.00"), "Points for a code review submitted."),
    ("ISSUE_CLOSED", Decimal("5.00"), "Points for resolving and closing an issue."),
    ("COMMIT", Decimal("1.00"), "Points per commit to org repositories."),
    ("RELEASE", Decimal("15.00"), "Points for publishing a release."),
    ("DISCUSSION", Decimal("3.00"), "Points for participating in a discussion."),
]


def seed_weights(apps, schema_editor):
    """Create default scoring weights."""
    ScoringWeight = apps.get_model("members", "ScoringWeight")
    for contribution_type, weight, description in DEFAULT_WEIGHTS:
        ScoringWeight.objects.get_or_create(
            contribution_type=contribution_type,
            defaults={"weight": weight, "description": description},
        )


def delete_weights(apps, schema_editor):
    """Remove seeded scoring weights."""
    ScoringWeight = apps.get_model("members", "ScoringWeight")
    ScoringWeight.objects.filter(
        contribution_type__in=[ct for ct, _, _ in DEFAULT_WEIGHTS]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_weights, delete_weights),
    ]
