# Generated by Django 6.0.3 on 2026-03-07 07:10

from django.db import migrations


DEFAULT_BADGES = [
    ("Architect", "Designed a major system or feature.", "Architect"),
    ("Visionary", "Proposed an accepted strategic initiative.", "Visionary"),
    ("Reviewer", "Completed 50+ code reviews.", "Reviewer"),
    ("Optimizer", "Significantly improved performance.", "Optimizer"),
    ("Guide", "Mentored a new member through onboarding.", "Guide"),
    ("Speaker", "Presented at a collective session.", "Speaker"),
    ("Hacker", "Won or placed in a hackathon.", "Hacker"),
    ("Fast Learner", "Completed a learning track ahead of schedule.", "FastLearner"),
    ("Newcomer", "Made first contribution to the collective.", "Newcomer"),
]


def seed_badges(apps, schema_editor):
    """Create default badge definitions."""
    Badge = apps.get_model("members", "Badge")
    for name, description, icon_name in DEFAULT_BADGES:
        Badge.objects.get_or_create(
            name=name,
            defaults={"description": description, "icon_name": icon_name},
        )


def delete_badges(apps, schema_editor):
    """Remove seeded badges."""
    Badge = apps.get_model("members", "Badge")
    Badge.objects.filter(name__in=[name for name, _, _ in DEFAULT_BADGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_seed_scoring_weights'),
    ]

    operations = [
        migrations.RunPython(seed_badges, delete_badges),
    ]
