# Generated by Django 6.0.3 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_add_line_contributions"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="monthly_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monthly weighted merit score (cached, recomputed periodically).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="weekly_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Weekly weighted merit score (cached, recomputed periodically).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="weekly_contribution_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total contributions in last week (cached).",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="monthly_contribution_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total contributions in last month (cached).",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="weekly_commits",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Commit count in the current calendar week.",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="monthly_commits",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Commit count in the current calendar month.",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="weekly_points",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Weighted points in the current calendar week.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="monthly_points",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Weighted points in the current calendar month.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="weekly_additions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lines added in the current calendar week.",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="weekly_deletions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lines deleted in the current calendar week.",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="monthly_additions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lines added in the current calendar month.",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="monthly_deletions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lines deleted in the current calendar month.",
            ),
        ),
    ]
