# Generated by Django 6.0.3 on 2026-03-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_add_period_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='monthly_additions',
            field=models.PositiveIntegerField(default=0, help_text='Total lines added in the current month (cached).'),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_deletions',
            field=models.PositiveIntegerField(default=0, help_text='Total lines deleted in the current month (cached).'),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_impact',
            field=models.PositiveIntegerField(default=0, help_text='Percentile rank among active members for the current month (cached).'),
        ),
        migrations.AddField(
            model_name='member',
            name='weekly_additions',
            field=models.PositiveIntegerField(default=0, help_text='Total lines added in the current week (cached).'),
        ),
        migrations.AddField(
            model_name='member',
            name='weekly_deletions',
            field=models.PositiveIntegerField(default=0, help_text='Total lines deleted in the current week (cached).'),
        ),
        migrations.AddField(
            model_name='member',
            name='weekly_impact',
            field=models.PositiveIntegerField(default=0, help_text='Percentile rank among active members for the current week (cached).'),
        ),
    ]
